language: python
python:
- '3.5'
- '3.6'
install: true
env:
  global:
  - REPOSITORY_USER=chadell
  - secure: PFMQ6cMIgcuxyM7uYY8kwWyNMwdkmNIZtfrGRiypBrqMb6UWqZdVkCzmKlnH3e7RPXdDoUBUA1G4kPGDGiJkpMvsZtJH3nSchu9rBg4ZMxif/uESZKx471UtcYk6wek3CL6Mzu2lKMGbYQpY4V1FHCttiXxMP/v1Ua8/b5+2raLj4Sj6q8LAwCxOgI/nqxVCJGAVk8juxhLcx+99l5CSXLxHNW1SBkdJNlscRSIVmZvaQByTaNA6duVftDiF0A3F4kvXtJX/GHXFdCMYkdLkHgEjl75UkFcPIUk+ojOo7TbX5uowAfEE0NR5QffuITcUBCdtB8FEW2i5IXbEzjCyQ0IKTP0bDHF7oi+yeyASpALGLXPwVWgMrxnD08cbPH9iC4bbYvw071rKOJHTRr9qQkxDaUqCrByxg/u8YQ0jTWPPDa8pmMIfX5ZXYsaPV9Snttkq+vU+uhzmxmxfP4xzshyefno1PXe3EXFJmAYfTa8VFTgY4HKxy2TSbilwq1stSX/XgnlG6O9gumOvrgkZbM/r5UX5mpj6CJnRESk7jxO2tVMX8dQW0DHKiCH1jM/5J5ltMi8OPX82MKWtAcr7Thu24NqtfyeEy/6W5FrCtLLkRJbALFayH3wmHTzprz4AaUgN0eLPzi5Ay00pV2F/jWAArPg+o+nsg0TEu+FHQPk=
script:
- "./script/cibuild"
deploy:
- provider: script
  skip_cleanup: true
  script: "./script/cideploy"
  on:
    python: 3.6
    tags: true
