language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements/test_requirements.txt
  - pip install -r requirements/requirements.txt
# command to run tests
script: scripts/test
