#!/bin/sh

set -xe

cd "$(dirname "$(readlink -f "$0")")/.."

if [ -z "$TRAVIS" ]; then
	echo "$0 should only be used in a CI environment like TravisCI"
	exit 1
fi

pip install --upgrade pip setuptools wheel virtualenv

pip install --requirement requirements/requirements.txt
pip install --requirement requirements/test_requirements.txt

pip install --editable .
